shawnkoh/SoftMark

backend/package.json
backend/src/controllers/PaperUsersController.ts
backend/src/entities/Annotation.ts
backend/src/entities/Bookmark.ts
backend/src/entities/Page.ts
backend/src/entities/PageQuestion.ts
backend/src/entities/Question.ts
backend/src/entities/Script.ts
backend/src/types/paperUsers.ts

Entity fixes

---

frontend/package.json
frontend/src/api/auth.ts
frontend/src/api/base.ts
frontend/src/api/index.ts
frontend/src/api/paperUsers.ts
frontend/src/api/papers.ts
frontend/src/components/buttons/AddButton.tsx
frontend/src/components/layouts/MainAppPages.tsx
frontend/src/components/layouts/MainLayout.tsx
frontend/src/db/selectors.ts
frontend/src/modules/papers/components/forms/SimpleForm.tsx
frontend/src/modules/papers/components/headers/PaperIndexHeader.tsx
frontend/src/modules/papers/components/headers/PaperViewHeader.tsx
frontend/src/modules/papers/components/modals/AddMarkerModal.tsx
frontend/src/modules/papers/components/modals/AddPaperModal.tsx
frontend/src/modules/papers/components/pages/PaperView.tsx
frontend/src/modules/session/components/SignInPage.tsx
frontend/src/modules/session/reducers.ts
frontend/src/theme/palette.ts
frontend/src/utils/options.ts

created a skeleton for the above pages

set up paper index and paper view

---

backend/src/controllers/ScriptsController.ts
backend/src/entities/Page.ts
backend/src/entities/Script.ts
backend/src/types/pages.ts
backend/src/types/scripts.ts
frontend/src/api/papers.ts
frontend/src/api/scripts.ts
frontend/src/modules/papers/components/pages/PaperIndex.tsx
frontend/src/modules/papers/components/pages/PaperView.tsx
frontend/src/modules/scripts/components/pages/ScriptView.tsx

Put image url in page model

---

backend/package.json
backend/src/controllers/QuestionTemplatesController.ts
backend/src/entities/Allocation.ts
backend/src/entities/Mark.ts
backend/src/entities/PaperUser.ts
backend/src/entities/Question.ts
backend/src/middlewares/canModifyMark.ts
backend/src/routes/api/questionTemplates.spec.ts
backend/src/routes/api/questionTemplates.ts
backend/src/server.ts
backend/src/types/questions.ts
yarn.lock

Logic to beat race condition works like a charm.
Take note that the QuestionData is not sufficient for the frontend. Just need to modify QuestionData type and Question.getData()
Take note @ooimingsheng @rlrh

Race Condition

---

frontend/src/components/buttons/ThemedButton.tsx
frontend/src/components/forms/SimpleForm.tsx
frontend/src/modules/papers/components/headers/PaperIndexHeader.tsx
frontend/src/modules/papers/pages/PaperIndex.tsx

Modify paper index

---

backend/src/constraints/IsUniqueFilename.ts
backend/src/constraints/IsUniqueSha256.ts
backend/src/controllers/PaperUsersController.ts
backend/src/controllers/PapersController.ts
backend/src/controllers/ScriptsController.ts
backend/src/controllers/UsersController.ts
backend/src/entities/PaperUser.ts
backend/src/entities/QuestionTemplate.ts
backend/src/entities/Script.ts
backend/src/entities/ScriptTemplate.ts
backend/src/entities/User.ts
backend/src/migrations/1571150302537-Initial.ts
backend/src/routes/api/annotations.spec.ts
backend/src/routes/api/marks.spec.ts
backend/src/routes/api/pages.spec.ts
backend/src/routes/api/papers.spec.ts
backend/src/routes/api/questionTemplates.spec.ts
backend/src/routes/api/questions.spec.ts
backend/src/routes/api/scriptTemplates.spec.ts
backend/src/routes/api/scripts.spec.ts
backend/src/types/questionTemplates.ts
backend/src/types/scripts.ts
backend/src/utils/tests.ts
frontend/package.json
frontend/src/api/scripts.ts
yarn.lock

* Fix constructors
* Rename Script.paperUser to student and make it optional
* Add filename and sha256 to Script
* Add IsUniqueFilename and IsUniqueSha256 constraints
* Remove unnecessary imports
* Update tests

Paper users

---

backend/package.json
backend/src/middlewares/checkEmailVerified.ts

This was preventing the previous fixes to the backend like the user's password being double hashed.

Fix failing backend build

---

backend/src/controllers/GradingController.ts
backend/src/controllers/QuestionTemplatesController.ts
backend/src/routes/api/papers.ts
backend/src/routes/api/scriptTemplates.ts
backend/src/types/questionTemplates.ts

Add GET /script_templates/:id/root_question_templates
Remove GET /papers/:id/question_templates

Add GET /script_templates/:id/root_question_templates

---

backend/src/controllers/UsersController.ts
backend/src/migrations/1571150302537-Initial.ts
frontend/src/UnauthenticatedApp/SignUpPage/SignUpForm/index.tsx
frontend/src/api/users.ts

Fix signup bug

---

backend/src/controllers/QuestionTemplatesController.ts
backend/src/entities/Allocation.ts
backend/src/entities/PageQuestionTemplate.ts
backend/src/entities/PageTemplate.ts
backend/src/entities/QuestionTemplate.ts
backend/src/entities/ScriptTemplate.ts
backend/src/routes/api/questionTemplates.spec.ts
backend/src/types/allocations.ts
backend/src/types/pageQuestionTemplates.ts
backend/src/types/pageTemplates.ts
backend/src/types/questionTemplates.ts
backend/src/types/scriptTemplates.ts
frontend/.vscode/settings.json
frontend/package.json
frontend/src/AuthenticatedApp/QuestionAllocationPage/components/MarkersTableRow.tsx
frontend/src/AuthenticatedApp/QuestionAllocationPage/index.tsx
frontend/src/AuthenticatedApp/paperSetup/ScriptTemplatePanel/index.tsx
frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateQuestion/index.tsx
frontend/src/api/auth.ts
frontend/src/api/client.ts
frontend/src/api/questionTemplates.ts
frontend/src/api/users.ts
frontend/src/store/auth/reducers.ts
yarn.lock

1. Fixes #117 
2. Replaces QuestionTemplateData with QuestionTemplateListData
3. Enables eslint

Replace retry axios with a custom interceptor

---

backend/src/controllers/AllocationsController.ts
backend/src/controllers/QuestionTemplatesController.ts
backend/src/routes/api/papers.ts
backend/src/utils/sorts.ts
frontend/src/AuthenticatedApp/PaperViewPage/subpages/Scripts/index.tsx
frontend/src/AuthenticatedApp/QuestionAllocationPage/components/MarkersTableRow.tsx
frontend/src/AuthenticatedApp/paperGrading/MarkQuestionPage/MarkQuestionModal.tsx
frontend/src/AuthenticatedApp/paperGrading/MarkQuestionPage/index.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptView/index.tsx

also fixed error thrown when no questions were allocated
also removed excess code

Add sort to scripts page

---

frontend/src/AuthenticatedApp/PaperIndexPage/index.tsx
frontend/src/AuthenticatedApp/PaperViewPage/components/PaperViewHeader.tsx
frontend/src/AuthenticatedApp/PaperViewPage/index.tsx
frontend/src/AuthenticatedApp/index.tsx
frontend/src/AuthenticatedApp/paperGrading/GradingPage/GradingTableRow.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptViewSubpage/index.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptsPage/index.tsx
frontend/src/AuthenticatedApp/paperSetup/QuestionAllocationSubpage/components/DeleteMarkerModal.tsx
frontend/src/AuthenticatedApp/paperSetup/SetupPage/index.tsx
frontend/src/AuthenticatedApp/paperSetup/components/tables/ScriptsTable.tsx
frontend/src/api/scripts.ts

- Added permissions  in file: "frontend/src/AuthenticatedApp/PaperViewPage/index.tsx"
pages are allowed depending on the role a user has for a particular paper i.e. owner, marker or student.
Note: student redirect route not tested
- Fixed rerender issue on scripts listing page
- Only show grade button if marker is assigned to particular question

Fix some issues and add permissions

---

backend/src/controllers/QuestionTemplatesController.ts
backend/src/routes/api/scriptTemplates.spec.ts
frontend/src/AuthenticatedApp/PaperViewPage/index.tsx
frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateSubpage/PageTemplateView/useStyles.ts
frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateSubpage/ScriptTemplateView/QuestionTemplateDialog.tsx

- Restrict `Question` creation to leaf question templates
- Fix not loading script_template setup route
- Fix FAB being covered by the page image
- Restrict questionTemplate.score to be positive
- Add delete cascade to the linked questions to question template

Minor fix to script-template

---

frontend/src/components/Canvas/Canvas.tsx
frontend/src/components/Canvas/CanvasWithToolbar.tsx

Increase default pen width

---

frontend/src/AuthenticatedApp/PaperViewPage/index.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptEditSubpage/Annotator.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptEditSubpage/MarkQuestionModal.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptEditSubpage/index.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptEditSubpage/styles.ts
frontend/src/AuthenticatedApp/paperScripts/ScriptsPage/ScriptsTableRow.tsx
frontend/src/AuthenticatedApp/paperScripts/index.ts
frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateSubpage/PageTemplateView/index.tsx

- New `Mark` button on each row in `Scripts` tab
- Possible fix for gradebox positioning

Individual script marking page; gradebox positioning possible fix

---

frontend/package.json
frontend/src/AuthenticatedApp/DownloadAsPdfPage/index.tsx
frontend/src/components/Canvas/CanvasSaver.jsx
yarn.lock

have not done logic to save all scripts or a particular script

Improve script pdf saver

---

frontend/src/AuthenticatedApp/DownloadAsPdfPage/index.tsx
frontend/src/AuthenticatedApp/PaperIndexPage/index.tsx
frontend/src/AuthenticatedApp/PaperViewPage/index.tsx
frontend/src/AuthenticatedApp/paperGrading/GradingPage/GradingTableRow.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptsPage/index.tsx
frontend/src/AuthenticatedApp/paperSetup/QuestionAllocationSubpage/components/AddMarkerModal.tsx
frontend/src/AuthenticatedApp/paperSetup/QuestionAllocationSubpage/components/MarkersTableRow.tsx
frontend/src/AuthenticatedApp/paperSetup/QuestionAllocationSubpage/index.tsx
frontend/src/AuthenticatedApp/paperSetup/SetupPage/index.tsx
frontend/src/AuthenticatedApp/paperSetup/components/modals/AddStudentModal.tsx
frontend/src/AuthenticatedApp/paperSetup/components/modals/DeleteAllScriptsModal.tsx
frontend/src/AuthenticatedApp/paperSetup/components/modals/DeleteAllStudentsModal.tsx
frontend/src/AuthenticatedApp/paperSetup/components/modals/DeleteScriptModal.tsx
frontend/src/AuthenticatedApp/paperSetup/components/modals/DeleteStudentModal.tsx
frontend/src/AuthenticatedApp/paperSetup/components/modals/PickStudentModal.tsx
frontend/src/AuthenticatedApp/paperSetup/components/tables/ScriptTableRow.tsx
frontend/src/AuthenticatedApp/paperSetup/components/tables/ScriptsTable.tsx
frontend/src/AuthenticatedApp/paperSetup/components/tables/StudentsTable.tsx
frontend/src/AuthenticatedApp/paperSetup/components/tables/StudentsTableRow.tsx
frontend/src/api/paperUsers.ts
frontend/src/api/scripts.ts
frontend/src/components/Canvas/CanvasSaver.jsx
frontend/src/components/uploadWrappers/UploadNominalRollWrapper.tsx
frontend/src/components/uploadWrappers/UploadScriptTemplateWrapper.tsx
frontend/src/components/uploadWrappers/UploadScriptsWrapper.tsx
frontend/src/contexts/ScriptsAndStudentsContext/index.tsx

- create students and scripts provider
- add match column on students table in map page
- add stats on map page

Create students and scripts provider

---

backend/src/controllers/PaperUsersController.ts
backend/src/controllers/ScriptsController.ts
backend/src/entities/Script.ts
backend/src/entities/ScriptTemplate.ts
backend/src/types/scriptTemplates.ts
backend/src/types/scripts.ts
frontend/src/AuthenticatedApp/DownloadAsPdfPage/index.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptsPage/PublishScriptsModal.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptsPage/ScriptsTableRow.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptsPage/index.tsx
frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateSubpage/ScriptTemplateView/QuestionTemplateDialog.tsx

Edit refactor students and scripts index routes to make them faster.
Use contexts for more pages
Switched off the filter on the publish page for now

Make scripts and students index routes faster and other small stuff

---

frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateSubpage/PageTemplateView/index.tsx
frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateSubpage/PageTemplateView/useStyles.ts
frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateSubpage/ScriptTemplateGradebox/index.tsx
frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateSubpage/ScriptTemplateView/QuestionTemplateDialog.tsx
frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateSubpage/ScriptTemplateView/QuestionTemplateTree.tsx
frontend/src/AuthenticatedApp/paperSetup/context/ScriptSetupContext.tsx

Attempt to resolve the issue of grade box being created outside of the image

Attempt to fix grade box creation issue

---

frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateSubpage/ScriptTemplateView/index.tsx

This reverts commit 868a18b0d40f023d2b391c9b380a37777e0dd9ee.

Revert "Attempt to fix touch on iPad (#217)"

---

backend/src/controllers/PaperUsersController.ts

Not the ideal solution, but the fastest.
Ideally, we should have a ScriptViewToken as mentioned here #208

Prevent students' paperUser from being deleted when they reject the invite

---

backend/src/controllers/PapersController.ts
backend/src/types/grading.ts

Fix grading route

---

frontend/src/AuthenticatedApp/paperSetup/ScriptTemplateSubpage/ScriptTemplateView/QuestionTemplateDialog.tsx
frontend/src/AuthenticatedApp/paperSetup/context/ScriptSetupContext.tsx

Fix question templates on the sidebar not updating when a question is deleted.

Fix ui refresh issue on script-template-setup page

---

backend/ormconfig.ts

PRODUCTION: Disable synchronize

---

backend/src/controllers/QuestionTemplatesController.ts
backend/src/controllers/ScriptsController.ts
backend/src/entities/Script.ts

MUST REBUILD PRODUCTION DB WITH SYNC ON AFTER THIS PR

Fix unexpected behaviour when creating a script

---

backend/src/controllers/AnnotationsController.ts
backend/src/controllers/QuestionTemplatesController.ts
frontend/src/AuthenticatedApp/paperGrading/MarkQuestionSubpage/Annotator.tsx
frontend/src/AuthenticatedApp/paperGrading/MarkQuestionSubpage/index.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptEditSubpage/index.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptMarkSubpage/index.tsx
frontend/src/AuthenticatedApp/paperScripts/ScriptViewSubpage/index.tsx
frontend/src/components/Canvas/CanvasSaver.jsx
frontend/src/components/uploadWrappers/UploadScriptTemplateWrapper.tsx

Revert "remove-annotator-rerender"

---

frontend/src/AuthenticatedApp/paperGrading/GradingPage/GradingTableRow.tsx

Fix rounding off error

---

backend/src/controllers/PaperUsersController.ts
backend/src/controllers/ScriptsController.ts
backend/src/entities/PaperUser.ts
backend/src/types/paperUsers.ts
frontend/src/AuthenticatedApp/paperGrading/MarkQuestionSubpage/Annotator.tsx
frontend/src/AuthenticatedApp/paperGrading/MarkQuestionSubpage/MarkQuestionModal.tsx
frontend/src/AuthenticatedApp/paperSetup/SetupPage/index.tsx
frontend/src/AuthenticatedApp/paperSetup/components/modals/EditStudentModal.tsx
frontend/src/AuthenticatedApp/paperSetup/components/tables/StudentsTable.tsx
frontend/src/AuthenticatedApp/paperSetup/components/tables/StudentsTableRow.tsx
frontend/src/types/paperUsers.ts

Revert "Add script file name mapping"

---

backend/src/controllers/AnnotationsController.ts
backend/src/entities/Annotation.ts

Previously, it was loading the entire page including the image on every stroke.

Optimise AnnotationsController.replace

---

backend/src/entities/ScriptTemplate.ts
backend/src/types/scriptTemplates.ts
frontend/src/AuthenticatedApp/paperSetup/components/tables/ScriptsTable.tsx

Optimisation to try to prevent server from crashing.

Remove pageTemplates data from ActiveScriptTemplate

---

backend/src/controllers/ScriptsController.ts
backend/src/controllers/ViewController.ts
backend/src/entities/Page.ts
backend/src/routes/api/scripts.spec.ts
backend/src/routes/api/scripts.ts
frontend/src/AuthenticatedApp/DownloadScriptsPages/components/ScriptsDownloader.tsx
frontend/src/AuthenticatedApp/paperSetup/components/modals/ViewScriptModal.tsx
frontend/src/api/scripts.ts
frontend/src/components/Canvas/CanvasSaver.jsx

Add marks to PDF download

---

yarn.lock

Revert "Yarn upgrade"

---

backend/src/server.ts
frontend/src/AuthenticatedApp/PaperViewPage/index.tsx
frontend/src/AuthenticatedApp/index.tsx

move context so scripts and students and script template contexts do not surround the student pages

Shift contexts

---

frontend/src/AuthenticatedApp/paperScripts/ScriptViewSubpage/index.tsx
frontend/src/AuthenticatedApp/theme.ts
frontend/src/components/Canvas/Canvas.tsx

Basic functionality for viewing of script.
UI may be slightly improved if I have time.

ScriptViewSubpage - show marking chips on page, show total marks chip

---

frontend/src/AuthenticatedApp/DownloadScriptsPages/components/ScriptsDownloader.tsx
frontend/src/components/Canvas/CanvasSaver.jsx

- Use JSPDF options to compress images and PDF
- Change back Konva pixel ratio to default as decreasing it has a drastic impact on quality but little change in file size

Compress generated PDF
